### ISSUE TITLE
Single-file executable backend

### ISSUE THREAD

**Issue by burnoutprojects** [hschneider/neutralino-ext-bun#2]
Hi there, bun provide single-file executable after compiled it down and i think this feature is  very good for code protection. Can you implement this feature to this repo?

Bun Docs: https://bun.sh/docs/bundler/executables

**Comment by hschneider** [comment]
Nice idea. I will look into it ...

**Comment by hschneider** [comment]
Done :-)

https://github.com/hschneider/neutralino-ext-bun/releases/tag/v1.0.4

**Comment by burnoutprojects** [comment]
Nice! I'm tested it, today and I shared the results here

**Comment by hschneider** [comment]
There are changes in the run scripts after 1.0.4. So you should test with the current codebase, not the 1.0.4 archives.

**Comment by burnoutprojects** [comment]
> There are changes in the run scripts after 1.0.4. So you should test with the current codebase, not the 1.0.4 archives.

I get the latest commits from main branch. After the initial tests i open a pull request to add Linux support.

**Comment by hschneider** [comment]
The macOS run script should work on Linux as well.

**Comment by burnoutprojects** [comment]
> The macOS run script should work on Linux as well.

For Linux you must add this line `"commandLinux": "${NL_PATH}/extensions/bun/run ${NL_PATH}"` inside `extensions` object to `neutralino.config.json`.

But is not currently running in Linux. I'm investigate the issue and i open a pull request with hotfix for the issue.

**Comment by burnoutprojects** [comment]
For reference the `neu run` return this message `exec format error: ./extensions/bun/_runtime/bin/bun` because failed to run bun runtime

**Comment by hschneider** [comment]
You need to copy the bun binary for Linux to the bin folder.

**Comment by hschneider** [comment]
Calling ./install.sh in the extension/bun folder should do. Assumed, that Bun is already installed on your system.

**Comment by burnoutprojects** [comment]
I already done this but the issue remain the same

**Comment by hschneider** [comment]
commandLinux added.

**Comment by hschneider** [comment]
Normally this error means that the binary has the wrong format for the current platform.
Can you successfully call `bun --version` ?
Ich so get its location with `which bun` and copy the binary from there to the bin folder.

**Comment by burnoutprojects** [comment]
I found the issue, the `NL_PATH` env is point to `.` not to relative path.

**Comment by burnoutprojects** [comment]
This is strange because in preview release i haven't this issue.

**Comment by hschneider** [comment]
Efcharistó ! :-)

**Comment by burnoutprojects** [comment]
Hahaha nice try my friend 😉. The issue is locate if you run the `install.sh` in the root of the project.

**Comment by hschneider** [comment]
I knew, this would amuse you ;)
Have some fix for install.sh, too?

**Comment by burnoutprojects** [comment]
I have a question for you, why you copy the bun binary inside the project? It's useless because you have this already, inside the path of the machine.

**Comment by hschneider** [comment]
Not on the customer's target machine. This way you deliver with batteries included ...

**Comment by burnoutprojects** [comment]
> Not on the customer's target machine. This way you deliver with batteries included ...

You have a good point on that, i don't think situation 😅

**Comment by burnoutprojects** [comment]
I have another idea and i think is very useful, but i can't wrap my mind around this. If the backend extension (aka bun) not running for some reason (error), kill the parent process (Neutralino)

**Comment by hschneider** [comment]
Think we can close this.  Thanks for the commit!
