### ISSUE TITLE
[Linux] Bun extension is not running after build  

### ISSUE THREAD

**Issue by burnoutprojects** [hschneider/neutralino-ext-bun#6]
Hi @hschneider, i'm testing the code yesterday and after the `neu build` i run the binary from `dist` folder but return this error `./dist/ext-bun/extensions/bun/run: line 5: ./dist/ext-bun/extensions/bun/_runtime/bin/bun: No such file or directory`. In my understand the `neu build` is not copy the `_runtime` folder. I'm running the program with the host `bun` runtime.  

I'm already trying to fix this and open a pull request with the fix later.

**Comment by burnoutprojects** [comment]
It's my fault, i forget to run the `install.sh` before build the app.

**Comment by hschneider** [comment]
No prob :-)
